{% set name = "HelioPy" %}
{% set version = "0.5.1" %}
{% set sha256 = "4b902854079f1572c47681e9662646355aeb29ab6304b10dc49fcca59bed31b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not py36]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - pandas
    - astropy
test:
  imports:
    - heliopy
    - heliopy.data
    - heliopy.util

about:
  home: http://heliopy.org/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Python for space physics'

  description: |
    HelioPy is a package for automatically downloading and reading in common
    data files used in space physics.
  doc_url: http://docs.heliopy.org/en/stable/
  dev_url: https://github.com/heliopython/heliopy

extra:
  recipe-maintainers:
    - dstansby
