{% set name = "HelioPy" %}
{% set version = "0.14.0" %}
{% set sha256 = "6e23f1d2196346538af485a931b583270a0a4e51adbb5e691ffb9c10fd88e70e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - astropy
test:
  imports:
    - heliopy

about:
  home: http://heliopy.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python for heliospheric physics
  description: |
    Tools to work with 1D in-situ timeseries measurements of space plasmas.
  doc_url: http://docs.heliopy.org/en/stable/
  dev_url: https://github.com/heliopython/heliopy

extra:
  recipe-maintainers:
    - dstansby
