{% set name = "HelioPy" %}
{% set version = "0.10.1" %}
{% set sha256 = "18970a9708bc31da5cded3e3021dca6ebe5a252cbc11e2d44d92b0c19f916824" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - astropy
test:
  imports:
    - heliopy

about:
  home: http://heliopy.org/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python for space physics
  description: |
    HelioPy is a package for heliospheric and planetary phsyics.
  doc_url: http://docs.heliopy.org/en/stable/
  dev_url: https://github.com/heliopython/heliopy

extra:
  recipe-maintainers:
    - dstansby
