travis:
  secure:
    BINSTAR_TOKEN: TntHK26Ega1fY1K8bGfX2PBX2L2M8sebjB2/usyqBQZRM8al94iNoimKaxLI4Hvvtj2oYhoj7ut4VpbCVAuAcTymfuthIEQ1rXGLYbSSsjHJ3rxOX9KO1lXfm4v0VvqPMSec3f0F1gI8qINQja+w1iIizU8dGrA47RXXSOLVfIjMOEzR6jU0fz3mNcSC61yscjrasPkr/5lmeTy9eC9w7QtyNYSjY8CGmQq/NwSbFD/6icR1IE/jiBJraKzv80QYkxEdoK2BGQOWjuqslLa8ecO4PK4VU7uOaWo1b3znRPpR7yBv+oQhzyO8Qn96FW1sqYDvsK9nObKtrxwdActznDX0uKzVZ58psU9ANRFewBH/YFA95MY4xf/by0JdMKmXjJqG5UlxQM5KfYPlbrY3H86XufzoDf62zfLFcGPSS8pNklzeYsprFcpTfkhoTJ0E21rhcDHOgAL8vVU2jzLi5uJ+9npZFqAXv0Uj33OTsi/at+5HSgsrx0NhvQgVTLFj2Fcy12bdhP/Wk5vqmWwFNxbSeHAiJzTcyOyCd49FBRoB86LFL0mQhEi2kGWBkLY19vemtVM5TOm/vjZUqTM8ud4AcnbLsjiQDVe5fac2TyEvL3b4nAAmUSO0bh0no7NLUnA0MU2a8udIzsWUdSqlYvbw3Oz3Bg4Qfk9GtMBWOwI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
