travis:
  secure:
    BINSTAR_TOKEN: RllNsODVyxojOO65+KNRQjIVylCh3lK1rWeWt2gldbVyD6FLH5oGFuJaZ8BO5qb1Qz2PhWdUV6qX2VJ89kgilJGayj3LR1wEfaRJv8Y8Es8odgME9MaKqW3lZQIEef2WVdiem0dvLuUbJpLAEIWeMkVKcDxiCzciWJbq9kyzb7G6Mci1S8LSB57r9naErK1Heqw5Ea/2jhtdCbjN9c/ZefkNZGEyT+F114OgO1zm20IWKXzXNIzGyUCw/M53QMZioMtpwv6Xw2V3jSFYxf8vajKZOL0qTsEo7T2rAhLXeGrUlizkPUSFakhgn3Ygee64AHWdqZ1SPpfJadkJ8H6K2ZMRo0HLZumvukZa215mSPAlMaWsXwe13Pftfgpwu5x8Z4nkX9neabETIMcXdIsruGUIzSJA7ej9N1dKjSv6p3TjEyHvR5RIw5vCd/mbZSC3zpCY2Tle6koah/C+bAGxKaOLqRSz0qi76IkpjRduSXRadMM5hgmA8/6zuMds4Wu/k5j+i3kTDvA/OXR5X52ksrhXHTbBrfWLSLBEGt9925MO4FIfzp2MZ7A7CvloKz1Y2e9yTh/wMN4CGJvarQo2YrgjvvG6RkU2Ab4R49OFYzymbJV8rNnd1tiQgpRa6L8r8g0n3O+JJHi4a0bP6h8LW2G4XcXnDiEwWGwvV0pebzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
